site_name: AGD_Handbook
site_url: https://agdh.hyjaxaru.xyz

nav:
  - Home: index.md

  - Essentials:
      - essentials/index.md
      - Variables: essentials/variables.md
      - Documenting your Code: essentials/docs.md

  - Tutorials:
      - tutorials/index.md
      - Shape Shooter:
          - tutorials/shape_shooter/index.md
          - Creating a New Project: tutorials/shape_shooter/step1.md
          - Sprites and Objects: tutorials/shape_shooter/step2.md
          - Creating a Room: tutorials/shape_shooter/step3.md
          - Making the Player Move: tutorials/shape_shooter/step4.md

  - Example:
      - placeholder_source/index.md

  - Rambles:
      - rambles/index.md
      - Digital NoteBook: rambles/notebook.md
      - The Time and Place for Vectors: rambles/vectors.md
      - The Semi-Colon Problem: rambles/semicolon.md

theme:
  name: material

  logo: assets/logo.png
  favicon: assets/favicon.ico

  custom_dir: docs/assets/overrides

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: green
      accent: teal

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: green
      accent: lime

  features:
    # - navigation.tabs.sticky
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

plugins:
  - tags
  - search
  - social

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:<noah.albrock@gmail.com>
      name: Email me
    - icon: fontawesome/brands/github
      link: https://github.com/Hyjaxaru
      name: Hyjaxaru on GitHub
    - icon: fontawesome/brands/discord
      link: https://discordapp.com/users/896071943382528101
      name: Hyjaxaru on Discord

copyright: Copyright &copy 2025 Hyjaxaru