# site details
site_name: AGD_Handbook
site_description: Essential resources for L6 Game Design, all in one place.
site_url: https://agdh.hyjaxaru.dev

# git repo details
repo_url: https://github.com/hyjaxaru/agdh  # github repo url
repo_name: AGD_Handbook                     # seems to be consmetic for the top-right corner
edit_uri: edit/main/docs/                   # path to docs. dont change this

# navigation tree
# allows you to specify the path of different docs
# while having a different folder structure
nav:
  - Home: index.md

  # essential links, aricles, etc
  - Essentials:
      - essentials/index.md
      - Variables: essentials/variables.md
      - Documenting your Code: essentials/docs.md

  # links to tutorials and even supports written ones
  - Tutorials:
      - tutorials/index.md
      # author: hyjaxaru
      - Shape Shooter:
          - tutorials/shape_shooter/index.md
          - Creating a New Project: tutorials/shape_shooter/step1.md
          - Sprites and Objects: tutorials/shape_shooter/step2.md
          - Creating a Room: tutorials/shape_shooter/step3.md
          - Making the Player Move: tutorials/shape_shooter/step4.md

  # placeholder source code examples
  - Example:
      - placeholder_source/index.md
  
  # random rambles that are somewhat interesting, and marginally related
  # feel free to add as many as you want
  - Rambles:
      - rambles/index.md
      - Digital NoteBook: rambles/notebook.md
      - The Time and Place for Vectors: rambles/vectors.md
      - The Semi-Colon Problem: rambles/semicolon.md

# theme data
# this is where the bulk of the customisation is
# see: https://squidfunk.github.io/mkdocs-material/
theme:
  name: material

  # icons
  logo: assets/logo.png
  favicon: assets/favicon.ico
  icon:
    repo: simple/github # top right corner with repo
    # edit: material/pencil # "edit this page" icon
    # view: material/eye # "view source of this page" icon

  # directory for override html files
  # see: https://squidfunk.github.io/mkdocs-material/customization/
  custom_dir: docs/assets/overrides

  # colour palette with light and dark themes
  # should automatically choose based on system theme
  # see: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"  # auto detect system theme
      scheme: default                         # material for mkdocs light mode
      toggle:                                 # toggle switch settings
        icon: material/weather-sunny          # icon
        name: Switch to dark mode             # tooltip
      primary: green                          # primary colour
      accent: teal                            # accent colour (links, etc)

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"   # auto detect system theme
      scheme: slate                           # material for mkdocs dark mode
      toggle:                                 # toggle switch settings
        icon: material/weather-night          # icon
        name: Switch to light mode            # tooltip
      primary: green                          # primary colour
      accent: lime                            # accent colour (links, etc) 

  # features
  # this decides how the docs act, and how they appear
  features:
    # - navigation.tabs.sticky      # sticks tabs to the top of the screen always
    - announce.dismiss              # dismiss button for top announcements
    - content.action.edit           # "edit this page" button
    - content.action.view           # "view source of this page" button
    - content.code.annotate         # annotations in code block comments
    - content.code.copy             # copy button in code blocks
    - content.tabs.link             # sync content tabs with similar names on a page
    - content.tooltips              # tooltips on links
    - navigation.footer             # footer navigation? (I forgot what this does exactly)
    - navigation.indexes            # allows categories to have a main page
    - navigation.instant            # stops the website from reloading for every internal link
    - navigation.instant.preview    # insiders feature, allows previewing of internal links
    - navigation.instant.progress   # page load progress indicator
    - navigation.sections           # sections
    - navigation.tabs               # top tabs for navigation
    - navigation.top                # top nav?
    - navigation.tracking           # updates the url with page position (anchors)
    - search.highlight              # highlights matches after search
    - search.share                  # unsure
    - search.suggest                # search suggestions
    - toc.follow                    # auto-scrolls the sidebar to match page position
    - toc.integrate                 # merges right sidebar into left

# plugins
# extra features that make the site better
plugins:
  - tags                            # tag system for pages
  - search                          # search for anything in the docs
  - social                          # embed links
  - git-committers:                 # shows who worked on a page
      repository: hyjaxaru/agdh     # repository excluding https://gthub.com
      branch: main                  # branch to link to
  - git-revision-date-localized:    # shows page creation and last edit dates
      enable_creation_date: true    # enabled showing page creation date

# extensions
# mostly dependancy for the markdown renderer, and `features` above
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# extra feature customisation
extra:
  # social plugin. Lets you set the icons that show at the bottom of the screen
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Hyjaxaru/agdh
      name: AGDH on GitHub

# copywrite notice
# I literally did 1 google search on how to write these
# sp feel free to correct
copyright: Copyright &copy 2025 Hyjaxaru