# site details
site_name: AGD_Handbook
site_description: Essential resources for L6 Game Design, all in one place.
site_url: https://agdh.hyjaxaru.dev # this must be accurate, or the social plugin will not work properly

# git repo details
repo_url: https://github.com/hyjaxaru/agdh
repo_name: AGD_Handbook
edit_uri: edit/main/docs/

# navigation tree
# allows you to specify the path of different docs
# while having a different folder structure
nav:
  - Home: index.md

  - Essentials:
      - essentials/index.md
      - Variables: essentials/variables.md
      - Documenting your Code: essentials/docs.md

  - Tutorials:
      - tutorials/index.md
      - Shape Shooter:
          - tutorials/shape_shooter/index.md
          - Creating a New Project: tutorials/shape_shooter/step1.md
          - Sprites and Objects: tutorials/shape_shooter/step2.md
          - Creating a Room: tutorials/shape_shooter/step3.md
          - Making the Player Move: tutorials/shape_shooter/step4.md

  - PlaceholderGame:
      - placeholder_game/index.md

  - Rambles:
      - rambles/index.md
      - Digital NoteBook: rambles/notebook.md
      - The Time and Place for Vectors: rambles/vectors.md
      - The Semi-Colon Problem: rambles/semicolon.md

# theme data
# this is where the bulk of the customisation is
# see: https://squidfunk.github.io/mkdocs-material/
theme:
  name: material

  # icons
  logo: assets/logo.png
  favicon: assets/favicon.ico
  icon:
    repo: simple/github # top right corner with repo
    # edit: material/pencil # "edit this page" icon
    # view: material/eye # "view source of this page" icon

  # directory for override html files
  # see: https://squidfunk.github.io/mkdocs-material/customization/
  custom_dir: docs/assets/overrides

  # colour palette with light and dark themes
  # should automatically choose based on system theme
  # see: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: green
      accent: teal

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: green
      accent: lime

  # features
  # this decides how the docs act, and how they appear
  features:
    # - navigation.tabs.sticky      # sticks tabs to the top of the screen always
    - announce.dismiss              # dismiss button for top announcements
    - content.action.edit           # "edit this page" button
    - content.action.view           # "view source of this page" button
    - content.code.annotate         # annotations in code block comments
    - content.code.copy             # copy button in code blocks
    - content.tabs.link             # sync content tabs with similar names on a page
    - content.tooltips              # tooltips on links
    - navigation.footer             # footer navigation? (I forgot what this does exactly)
    - navigation.indexes            # allows categories to have a main page
    - navigation.instant            # stops the website from reloading for every internal link
    - navigation.instant.preview    # insiders feature, allows previewing of internal links
    - navigation.instant.progress   # page load progress indicator
    - navigation.sections           # sections
    - navigation.tabs               # top tabs for navigation
    - navigation.top                # top nav?
    - navigation.tracking           # updates the url with page position (anchors)
    - search.highlight              # highlights matches after search
    - search.share                  # unsure
    - search.suggest                # search suggestions
    - toc.follow                    # auto-scrolls the sidebar to match page position
    - toc.integrate                 # merges right sidebar into left

# plugins
# extra features that make the site better
plugins:
  - tags                          # tag system for pages
  - search                        # search for anything in the docs
  - social                        # embed links
  - git-committers:               # shows who worked on a page
      repository: hyjaxaru/agdh
      branch: main
  - git-revision-date-localized:  # shows page creation and last edit dates
      enable_creation_date: true

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://hyjaxaru.dev
      name: My Other Work
    - icon: fontawesome/brands/github
      link: https://github.com/Hyjaxaru/agdh
      name: AGDH on GitHub

copyright: Copyright &copy 2025 Hyjaxaru